### PR TITLE
Fixes syntax error and removes is_sudo

### PR DESCRIPTION
**Pull request by bpswim90**

### CODE REVIEW

**Comment by katerberg** [comment]
Fixes https://github.com/katerberg/minimal-react/issues/15

**Comment by katerberg** [comment]
Fixes https://github.com/katerberg/minimal-react/issues/16

**Comment by kelseyjo959** [comment]
I was running mac OS Sierra on a VM and I was able to run the mongo-setup script successfully with the changes made.

**Comment by bpswim90** [comment]
Fixes https://github.com/katerberg/minimal-react/issues/16

**Pull request merged**
